# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3020fb09542aa27007eca91e56cf2e957ecdb1a1c432cef44fbeb3bdb7bbe6fa72bb595855b1e64295e2dbabb0bf8c36872954e5e0a7fba904a710b4f4d19674

test:
  secret_key_base: 17f9b7b8990e636c3ddbb2cb3832c4473dbcd550ce27575be73251cae12a14588f7c61f56d12c796082e165f9bede123fd5d41ee105f56bf163f150ecc08959b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
